function R = stage_rotation(about_z,about_y)
% R = stage_rotation(about_z,about_y)
% builds the rotation matrix that transforms a vector from stage coordinate 
% to beamcoordinate system.
% the stage consists of two rotations, the first rotation happens about the
% y axis and the second rotation about the z axis
%  

theta   = about_y;   % Pitch angle
psi     = about_z;   % Yaw angle

Rz = [ ...
     cos(psi), -sin(psi), 0; ...
     sin(psi),  cos(psi), 0; ...
            0,         0, 1 ...
    ];

Ry = [ ...
     cos(theta), 0, sin(theta); ...
              0, 1,          0; ...
    -sin(theta), 0, cos(theta) ...
    ];


R = Ry*Rz;
% R = Rz*Ry;
